language: c

# Enable when packages are whitelisted

#sudo: false
#
#addons:
#  apt:
#    packages:
#    - bc
#    - libkqueue0
#    - libkqueue-dee

before_install:
- sudo apt-get update -qq
- sudo apt-get install bc libkqueue-dev libkqueue0 git -qq
- git clone https://github.com/vstakhov/libucl.git && cd libucl && cmake . && make && sudo make install

script:
- make
- make check
